# Generated by Django 5.2.5 on 2025-08-15 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='display_order',
        ),
    ]
